# Generated by Django 4.2 on 2023-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Task name")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Task description"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Complete"),
                ),
                ("deadline", models.DateField()),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
